name: Setup python workflow test
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
      # Step 2: Set up Java with the JetBrains distribution for both versions
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: requirements*.txt

      - name: Install dependencies f
        run: |
          pip --version
          pip install -r requirements.txt        
        
